from mitulib import *

half_beat = 0.25
elements = [BeginElement(BeginElement.MODE_FREE),
            # 第一行
            DeltaTimeElement(half_beat * 2),
            MidiElement(0, 9, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 9, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 11, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 9, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 8, 0),
            DeltaTimeElement(half_beat * 2),
            MidiElement(0, 9, 0),
            DeltaTimeElement(half_beat * 2),
            MidiElement(0, 8, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 7, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 9, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 9, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 9, 0),
            DeltaTimeElement(half_beat * 2),
            MidiElement(0, 7, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 7, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 7, 0),
            DeltaTimeElement(half_beat * 2),
            # 第二行
            MidiElement(0, 9, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 9, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 9, 0),
            DeltaTimeElement(half_beat * 2),
            MidiElement(0, 7, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 7, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 7, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 9, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 9, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 9, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 9, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 9, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 11, 0),
            DeltaTimeElement(half_beat * 2),
            MidiElement(0, 9, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 11, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 11, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 9, 0),
            DeltaTimeElement(half_beat),
            DeltaTimeElement(half_beat * 2),
            # 第三行
            DeltaTimeElement(half_beat * 3),
            MidiElement(0, 8, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 8, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 7, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 8, 0),
            DeltaTimeElement(half_beat * 2),
            MidiElement(0, 7, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 8, 0),
            DeltaTimeElement(half_beat),
            DeltaTimeElement(half_beat),
            MidiElement(0, 8, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 8, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 7, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 8, 0),
            DeltaTimeElement(half_beat * 2),
            MidiElement(0, 7, 0),
            DeltaTimeElement(half_beat),
            MidiElement(0, 5, 0),
            DeltaTimeElement(half_beat),
            DeltaTimeElement(half_beat),
            MidiElement(0, 8, 0),
            DeltaTimeElement(half_beat),
            ]

order = Mitu.make(elements)
id_in_database = 27

sql = "update `ArchiveTable` set `ArchiveJSON` = '" + order + "' where ArchiveID = " + str(id_in_database) + ";"

print(sql)
