from MiTulib import *

"""
歌唱祖国
"""

quarter_beat = 0.1
instrument = 6

toneElements = [
    # 第一行
    MidiElement(instrument, 11, 0),
    DeltaTimeElement(quarter_beat),
    MidiElement(instrument, 11, 0),
    DeltaTimeElement(quarter_beat),
    MidiElement(instrument, 11, 0),
    DeltaTimeElement(quarter_beat * 6),
    MidiElement(instrument, 11, 0),
    DeltaTimeElement(quarter_beat),
    MidiElement(instrument, 11, 0),
    DeltaTimeElement(quarter_beat),
    MidiElement(instrument, 11, 0),
    DeltaTimeElement(quarter_beat * 6),
    MidiElement(instrument, 11, 0),
    DeltaTimeElement(quarter_beat),
    MidiElement(instrument, 11, 0),
    DeltaTimeElement(quarter_beat),
    MidiElement(instrument, 11, 0),
    DeltaTimeElement(quarter_beat * 2),
    MidiElement(instrument, 10, 0),
    DeltaTimeElement(quarter_beat * 2),
    MidiElement(instrument, 9, 0),
    DeltaTimeElement(quarter_beat * 2),
    MidiElement(instrument, 8, 0),
    DeltaTimeElement(quarter_beat * 2),
    MidiElement(instrument, 7, 0),
    DeltaTimeElement(quarter_beat * 4),
    MidiElement(instrument, 4, 0),
    DeltaTimeElement(quarter_beat * 3),
    MidiElement(instrument, 11, 0),
    DeltaTimeElement(quarter_beat),
    # 第二行
    MidiElement(instrument, 7, 0),
    DeltaTimeElement(quarter_beat * 4),
    MidiElement(instrument, 4, 0),
    DeltaTimeElement(quarter_beat * 4),
    MidiElement(instrument, 9, 0),
    DeltaTimeElement(quarter_beat * 4),
    MidiElement(instrument, 7, 0),
    DeltaTimeElement(quarter_beat * 4),
    MidiElement(instrument, 11, 0),
    DeltaTimeElement(quarter_beat * 6),
    MidiElement(instrument, 12, 0),
    DeltaTimeElement(quarter_beat * 2),
    MidiElement(instrument, 11, 0),
    DeltaTimeElement(quarter_beat * 4),
    MidiElement(instrument, 11, 0),
    DeltaTimeElement(quarter_beat * 3),
    MidiElement(instrument, 11, 0),
    DeltaTimeElement(quarter_beat),
    MidiElement(instrument, 14, 0),
    DeltaTimeElement(quarter_beat * 4),
    MidiElement(instrument, 14, 0),
    DeltaTimeElement(quarter_beat * 4),
    # 第三行
    MidiElement(instrument, 12, 0),
    DeltaTimeElement(quarter_beat * 3),
    MidiElement(instrument, 11, 0),
    DeltaTimeElement(quarter_beat),
    MidiElement(instrument, 10, 0),
    DeltaTimeElement(quarter_beat * 2),
    MidiElement(instrument, 12, 0),
    DeltaTimeElement(quarter_beat * 2),
    MidiElement(instrument, 11, 0),
    DeltaTimeElement(quarter_beat * 8),
    MidiElement(instrument, 11, 0),
    DeltaTimeElement(quarter_beat * 4),
    MidiElement(instrument, 11, 0),
    DeltaTimeElement(quarter_beat * 3),
    MidiElement(instrument, 11, 0),
    DeltaTimeElement(quarter_beat),
    MidiElement(instrument, 12, 0),
    DeltaTimeElement(quarter_beat * 4),
    MidiElement(instrument, 12, 0),
    DeltaTimeElement(quarter_beat * 4),
    MidiElement(instrument, 8, 0),
    DeltaTimeElement(quarter_beat * 4),
    MidiElement(instrument, 8, 0),
    DeltaTimeElement(quarter_beat * 3),
    MidiElement(instrument, 8, 0),
    DeltaTimeElement(quarter_beat),
    # 第四行
    MidiElement(instrument, 11, 0),
    DeltaTimeElement(quarter_beat * 6),
    MidiElement(instrument, 10, 0),
    DeltaTimeElement(quarter_beat * 2),
    MidiElement(instrument, 9, 0),
    DeltaTimeElement(quarter_beat * 4),
    MidiElement(instrument, 4, 0),
    DeltaTimeElement(quarter_beat * 3),
    MidiElement(instrument, 4, 0),
    DeltaTimeElement(quarter_beat),
    MidiElement(instrument, 11, 0),
    DeltaTimeElement(quarter_beat * 4),
    MidiElement(instrument, 11, 0),
    DeltaTimeElement(quarter_beat * 2),
    MidiElement(instrument, 12, 0),
    DeltaTimeElement(quarter_beat * 2),
    MidiElement(instrument, 13, 0),
    DeltaTimeElement(quarter_beat * 2),
    MidiElement(instrument, 11, 0),
    DeltaTimeElement(quarter_beat * 2),
    MidiElement(instrument, 12, 0),
    DeltaTimeElement(quarter_beat * 2),
    MidiElement(instrument, 13, 0),
    DeltaTimeElement(quarter_beat * 2),
    MidiElement(instrument, 14, 0),
    DeltaTimeElement(quarter_beat * 8),
    MidiElement(instrument, 14, 0),
    DeltaTimeElement(quarter_beat * 4),
]
elements = [BeginElement(BeginElement.MODE_FREE),
            LoopElement(toneElements),
            ]

order = MiTu.make(elements)
id_in_database = 2

sql = "update `ArchiveTable` set `ArchiveJSON` = '" + order + "' where ArchiveID = " + str(id_in_database) + ";"

print(sql)
